name: base_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  micro_core:
    git:
      url: https://github.com/guiqmaia/micro_core.git
      ref: v1.0.3

  micro_app_home:
    git:
      url: https://github.com/guiqmaia/micro_app_home.git
      ref: v1.0.4

  micro_app_login:
    git:
      url: https://github.com/guiqmaia/micro_app_login.git
      ref: v1.0.9
  micro_app_stocks:
    git:
      url: https://github.com/guiqmaia/micro_app_stocks.git
      ref: v1.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
